### PR TITLE
Add flags & premium type to User

### PR DESCRIPTION
**Pull request by vince614**

### CODE REVIEW

**Comment by chonsser** [comment]
Hey @vince614 - it's great to see your pull request. I have a single question - why the `isBot` and other getters like `isMfaEnabled` have changed to non-strict return values? All other changes are good.

**Comment by vince614** [comment]
Hay @chonsser, I remove them because they are not mandatory.

**Review by chonsser — APPROVED** [review]
Ok. I'll make a new 1.0.11 release for these changes. Thanks for your support @vince614!

**Comment by chonsser** [comment]
Hey @vince614 - your pull request broke the tests. I've updated the tests to match your new features and added an additional test check on every new pull request. The latest version of this OAuth provider lib is v1.1.0 which requires PHP 7.3. 

Cheers!

**Pull request merged**
